### ISSUE TITLE
Remove "operations" from jsonpatchdoc envelope

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/JsonPatch#1]

**Comment by sergkr** [comment]
For the time being, until this is actually implemented, you should add a note in the README for what the structure of the JSON patch document itself should look like in order to work with the library - it took a bit of monkeying around / digging through the source to find out.

    {
        "Operations": [
            { "op": "add", "path": "/foo", "value": "bar"},
            { "op": "replace", "path": "/baz", "value": "boo" }
        ]
    }

**Comment by KevinDockx** [comment]
Yup, good idea - done.

**Comment by KevinDockx** [comment]
Fixed in source - will be included in next release, after which readme will be updated
