### ISSUE TITLE
Null Reference Exception when trying to copy a null value

### ISSUE THREAD

**Issue by paulparas** [KevinDockx/JsonPatch#100]
Hi
I'm getting a Null Reference Exception when trying to copy a null value. Is it desired behaviour?
[  
  {
    "path": "addressLine3",
    "op": "copy",
    "from": "addressLine2"
  }
]
Here addressLine2 is null.

Thank you!
Regards
Paras Paul

**Comment by KevinDockx** [comment]
Hi @mklaber , I'm happy to accept a PR! :)

**Comment by mklaber** [comment]
@KevinDockx #107 is ready at your leisure. (As is #108 )

**Comment by KevinDockx** [comment]
Thanks a lot @mklaber  - just merged both PR's, I'll release an RC to NuGet & a final version next week (if no issues are reported from the RC).

**Comment by mklaber** [comment]
Thanks for getting to it so quickly @KevinDockx ! 

~~Any chance you can push the RC to nuget? Or use GitHub [packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry)? My work is going in to QA in the next day or two and could help identify issues. (And my company's infrastructure isn't well suited for libraries that aren't in nuget.)~~

Never mind. Reread your comment :)

**Comment by KevinDockx** [comment]
Here you go :) => https://www.nuget.org/packages/Marvin.JsonPatch/2.1.1-rc

**Comment by mklaber** [comment]
Shouldn't that be something like `2.2.1-rc` ? (given the latest is `2.2.0`)

**Comment by KevinDockx** [comment]
Woops - that's what happens when I try to quickly release something using a freshly-installed environment due to not having worked on it for a while :)  Here you go: https://www.nuget.org/packages/Marvin.JsonPatch/2.2.1-rc

**Comment by mklaber** [comment]
Don't make me jealous with your fancy new environment and your "dot net core" (or whatever the kids are calling it these days...)...

**Comment by KevinDockx** [comment]
Haha, alright, valid point ;-)
