### ISSUE TITLE
core 3.1 support? 

### ISSUE THREAD

**Issue by william1benn** [KevinDockx/JsonPatch#101]
Reading through your documentation it says if we are using .Net core we do not need this. Yet 3.1 does not seem to be supported as I cannot import it into my controller, and this is in Microsoft's documentation as well.

Any idea when this will be natively supported in 3.1 .net core? 
_https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.jsonpatch.jsonpatchdocument?view=aspnetcore-3.0_

![Screen Shot 2020-11-05 at 4 40 13 PM](https://user-images.githubusercontent.com/50754143/98299390-a2f4dd80-1f85-11eb-8ec5-b68d28ab492a.png)

**Comment by KevinDockx** [comment]
Hi William,

it is supported in 3.1, seems like that documentation is a bit off.  You just need to add the https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/ package.  On that link you can find matching versions for each major/minor .NET Core version.
