### ISSUE TITLE
Use media type application/json-patch+json

### ISSUE THREAD

**Issue by sergkr** [KevinDockx/JsonPatch#13]
According to the [spec](http://tools.ietf.org/html/rfc6902), JSON patch documents should really be using media type `application/json-patch+json`, instead of `application/json`. Just peeking at how the [competing library](https://github.com/myquay/JsonPatch) accomplished this, looks like you'll need to define a [custom formatter](https://github.com/myquay/JsonPatch/blob/master/src/JsonPatch/Formatting/JsonPatchFormatter.cs) and have the user of the library register it in their startup Web API config code.

**Comment by KevinDockx** [comment]
Sergey,

thanks for logging this!

**Comment by KevinDockx** [comment]
Hi Sergey,

I found some more time to look into this, but I don't think this is fully correct.  This is from the spec:

```
A JSON Patch document is a JSON [RFC4627] document that represents an
   array of objects.  Each object represents a single operation to be
   applied to the target JSON document.

   The following is an example JSON Patch document, transferred in an
   HTTP PATCH request:

   PATCH /my/data HTTP/1.1
   Host: example.org
   Content-Length: 326
   Content-Type: application/json-patch+json
   If-Match: "abc123"

   [
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
   ]
```

So: the patchdocument itself, that's the list of operations in JSON format.  The example you see here with the content-type specified, that's a full Http Patch Request, not just a patchdocument.  Setting the content-type to application/json-patch+json, that's what would typically happen by the component that creates the request (in .NET: HttpRequest with a custom header for content-type, the jsonpatchdocument as content and method PATCH). 

So: it's not part of the scope of using this library on the client: in the example in the readme, you can see it's still the client's responsibility to create the HttpRequest.  Marvin.JsonPatch doesn't create an HttpRequest message, it creates the JsonPatchDocument that's the content of such a request message.

As far as the server is concerned: at Web API level, I could require that content-type to be set to application/json-patch+json to allow it to work  - but that would mean clients that send HttpRequests to PATCH that don't specifically the content-type to application/json-patch+json will fail.   I'd rather consider this as an optional configuration server-side than making this a hard-set requirement.  

What do you think?

**Comment by sergkr** [comment]
> As far as the server is concerned: at Web API level, I could require that content-type to be set to application/json-patch+json to allow it to work

Sorry, I should have made it a bit more clear, but that's what I really meant when I submitted this issue.

> but that would mean clients that send HttpRequests to PATCH that don't specifically the content-type to application/json-patch+json will fail. I'd rather consider this as an optional configuration server-side than making this a hard-set requirement.

I think making it an optional configuration would be a good compromise.  What's critical here, in my view, is that you should support valid requests that fully comply with the spec. So if the client sends a PATCH request with the Content-Type correctly set to `application/json-patch+json`, it should work. You can choose to be lenient and also allow `application/json`, but that should be considered a "bonus" - supporting the correct use case should be first priority.

**Comment by KevinDockx** [comment]
Indeed - currently, the default web api config will throw "invalid media type" error with that content-type.  I'll look into the best way to fix this, ie: make it part of this lib, or make it part of the requirements for configuring web api to allow it to work with patch requests.

**Comment by KevinDockx** [comment]
To clarify this a bit more: to allow support for that media type, it's sufficient to ensure Web API can handle this.  In case of a JsonFormatter, that's a matter of adding the following line of code to Web API's config:

```
 config.Formatters.JsonFormatter.SupportedMediaTypes.Add(
                new MediaTypeHeaderValue("application/json-patch+json"));
```

Like that, PATCH requests with content-type application/json-patch+json and those with content-type application/json will be supported.  

So I'm thinking of:
1) putting that in the readme to state that's a requirement for supporting the correct media type according to spec => ie: no extra code in marvin.jsonpatch for this.
2) add an optional "strict" option that will block requests without that correct media type => that will become part of marvin.jsonpatch.

What do you think? :)

**Comment by sergkr** [comment]
Sorry for slow response - I've been out traveling the past couple days.

Your suggestion of putting it in the readme to add `application/json-patch+json` to the supported media types of the default JSON formatter should work, I think. A JSON patch document is technically a valid JSON document, so the default JSON formatter can be used for it.

However, if you go that route, I'm not sure how easily you'll be able to accommodate the second part (the "strict" option). You would need a way to get the request's content type from inside your custom JSON converter (`TypedJsonPatchDocumentConverter`), and I don't know if you have access to it at that point. That's the downside that I'm seeing... but maybe you had a different idea of how to go about accomplishing this?

If you instead go the custom formatter route, the formatter will only run for the media types you specify (which you can do in the constructor). And if the user of the library wants to also accept `application/json` for PATCH, then they can just add `application/json` to the `SupportedMediaTypes` list of your custom formatter (and you can put that in the readme - or you can add a `strict` option in your library, like you suggested, and add `application/json` to `SupportedMediaTypes` yourself in the constructor).

So I would lean towards defining a custom formatter (unless you know of a way to implement the "strict" option like you proposed that I'm not seeing).

Here's another (potential) consideration: error handling. Error handling probably deserves its own separate issue, as there are a lot of considerations there, but since it will affect the decision of whether to use a custom formatter or not (which we're currently discussing), it's probably worth mentioning a couple things about it here.

In the [error handling](https://tools.ietf.org/html/rfc6902#section-5) portion of the JSON Patch spec, it refers you to [RFC5789](https://tools.ietf.org/html/rfc5789#section-2.2), where it says if the user sends a malformed patch document, the server should return an HTTP 400 (Bad Request) response. Ideally, this is something that you should do in your library (so the user of the library shouldn't even have to worry about this). And just to be clear, we're not necessarily talking about just malformed JSON here - they might be sending you valid JSON, but not a valid JSON patch document (e.g., sending an object instead of an array at the root).

Currently, if they send a malformed patch document, you're just throwing a `JsonPatchException`, and I think that's probably fine for now. Even if you go the custom formatter route, you would still have a hard time implementing what the spec says, because you don't have access to the HTTP context (request/response) inside a formatter:

http://aspnetwebstack.codeplex.com/workitem/82

At least you don't have *easy* access - because you actually can get to it [as explained here](http://stackoverflow.com/questions/11494108/how-to-get-httprequestmessage-instead-of-httpcontext-current-in-webapi) (which is also alluded to in that codeplex issue). But that's something you can only do inside a formatter, as far as I know - so it might be another argument for going the custom formatter route.

However, error handling is a complex topic - the user of the library may want to do error logging, and maybe have full control over the response, in which case you would be doing them a major disfavor if you implement the spec to the letter without making it configurable. If you're going to be helping out with adding JSON Patch support to MVC 6 (I'm aware that's under consideration right now), you may want to touch base with the team on what's the best way to approach this.

FYI, on the topic of MVC 6, in case you're not aware, the whole concept of formatters has [changed](http://www.strathweb.com/2014/11/formatters-asp-net-mvc-6/):

> While in ASP.NET Web API formatters were bi-directional – single object handling both input and output, in MVC 6 the concept of formatters became uni-directional.

So for MVC 6, and assuming you go the formatters route, you would probably want to define a `JsonPatchInputFormatter` (I don't think you need an output formatter, because the response to a JSON Patch request doesn't need to be anything special, and it's up to the user of the library to send a response anyway). You may want to look at how they defined the default input/output formatters here:

https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNet.Mvc.Core/Formatters

**Comment by KevinDockx** [comment]
Thanks for the input!

In the long run, a custom formatter indeed seems the way to go - that'd then be used to implement the "strict" option.  I'd like to ensure current users can keep using the component without having to change too much code on a new release - I'd prefer not to break current implementation too much, even though v1 hasn't been reached yet :)  That said, there's not that much difference for consumers of the component in having to use the custom formatter or adding the mediatype to the default JSON formatter.

- so, for non-strict implementations => readme for now, convenient road to custom formatter later
- for a better, stricter implementation, I'll go the custom formatter route

In the end, the default way to go will thus be the custom formatter.

I split up error handling => issue 14.

For MVC6, that's a different ballgame altogether :)  I'll definitely touch base with the team on the best way to implement this.

**Comment by KevinDockx** [comment]
Sergey,

I've been thinking about this a bit more.  The media type application/json-patch+json is used to identify patch docs, but the content is in fact JSON, and according to the spec, will stay that way:

"A JSON Patch document is a JSON [RFC4627] document that represents an array of objects.  Each object represents a single operation to be applied to the target JSON document."

As far as formatters go (copy/pasting here :)): 

"Formatters give your service the flexibility to respond to a client with the same data but in an arbitrary format depending on what the client has asked for. If a client asks for application/json, your service will use the JSON formatter to respond with JSON."

So, with this in mind, it's starting to feel wrong to use a custom formatter to allow/block content-type "application/json-patch+json" - it's in fact JSON, so the JSON formatter should be sufficient. 

Thinking about this a bit more, this reminded me of a versioning strategy for REST-ful API's that's often used: content negotiation, where you put the version in the accept header through a custom media type and ensure that, through checking that header, the request is routed to the correct piece of code.  That's done with a custom route constraint (IHttpRouteConstraint).

Looking at JsonPatch, that would mean that such a custom IHttpRouteConstraint could be used to block a PATCH request IF it doesn't define it's content type as application/json-patch+json (well, in fact, it prevents a route from matching a request).  Eg: we're blocking the request, because the request is malformed, and that can be done through such a constraint.  No requirement for a custom formatter, and the added functionality that you can use such a constraint scoped to a route, scoped to a controller or even scoped to specific methods.  

What would you think of that approach?

**Comment by sergkr** [comment]
> So, with this in mind, it's starting to feel wrong to use a custom formatter to allow/block content-type "application/json-patch+json" - it's in fact JSON, so the JSON formatter should be sufficient.

Yeah, I see your point. And in any case, I don't think you'd be able to block `application/json` in the custom formatter if you only register it for `application/json-patch+json` (the formatter wouldn't even run if the request had content type `application/json`).

> Looking at JsonPatch, that would mean that such a custom IHttpRouteConstraint could be used to block a PATCH request IF it doesn't define it's content type as application/json-patch+json (well, in fact, it prevents a route from matching a request). Eg: we're blocking the request, because the request is malformed, and that can be done through such a constraint. No requirement for a custom formatter, and the added functionality that you can use such a constraint scoped to a route, scoped to a controller or even scoped to specific methods.

So they'd have to add this constraint individually to each controller (if they're using attribute based routing), or to each route (if they're using centralized routing)? Is there a way that you're aware of to add it globally?

You know, honestly, I'm beginning to wonder if blocking `application/json` for PATCH (this whole `strict` option thing) really ought to be out of scope for the library. Personally, I'd be fine with just adding it to the readme to say that they should add `application/json-patch+json` to the list of supported media types of the default JSON formatter, and leaving it at that.

**Comment by KevinDockx** [comment]
Afaik there's no way to auto-add it to all the routes, but you could write a helper that runs through the routes collection and adds the constraints - in fact, with that in mind I could include an "init" method, bool strict=true/false as param, that auto-adds the custom media type to the default formatter and, if strict=true, adds the constraint to all routes.  That would thus mean 1 line of code to set it all up for the end user.

And indeed, it isn't top priority :-) but I do want to add the ability to block non-correct request messages, if only to adhere to the spec :)

**Comment by KevinDockx** [comment]
Closed - in accordance with the implementation in ASP .NET, this component won't require this media type.  Will work with application/json and application/json-patch+json (and other json-related media types - as long as the document can be deserialized from JSON, it will work).
