### ISSUE TITLE
path with duplicate numbers may be truncated

### ISSUE THREAD

**Issue by masonhunk** [KevinDockx/JsonPatch#22]
Hello,
      I'm a user of Marvin.JsonPatch, and recently I got a problem.
      When I try to apply a value to a path like this, "\ArrayProp\0\SubArray\0", the value will be applied to "\ArrayProp\0". I guess in ObjectAdapter.cs, here may be the reason:
    "   actualFromProperty = operation.from.Substring(0,
                    operation.from.IndexOf('/' + positionAsInteger.ToString()));"
      If "IndexOf" is replaced by "LastIndexOf", may things get better?:)
      Expecting your respond:)

Kind regards.

**Comment by KevinDockx** [comment]
Thanks for logging this! :)  I'll check this out - will have to look into whether or not this fits the standard (eg: if what you're trying to do is allowed behaviour or not).  But either way, it looks like it how it's currently handling this is a bug - either the behaviour should be implemented as you suggest, or a clear JsonPatchException should be thrown.

I'll get back to you :)

**Comment by masonhunk** [comment]
Great. Thanks for the response！ :-)
Btw, the project of "Microsoft.AspNet.Jsonpatch" seems to be migragated from Marvin.JsonPatch,so will this "path truncating bug" fixed in next release of "Microsoft.AspNet.JsonPatch" either?

**Comment by KevinDockx** [comment]
Yes, I'm working on JsonPatch in AspNetvNext, so any and all bugs fixed here will also be fixed in AspNet.

**Comment by masonhunk** [comment]
Great ,thanks!

**Comment by KevinDockx** [comment]
It looks like a patch operation as you suggest should indeed be valid, cfr:

{ "comment": "Adding to \"/-\" adds to the end of the array, even n levels down",
      "doc": [ 1, 2, [ 3, [ 4, 5 ] ] ],
      "patch": [ { "op": "add", "path": "/2/1/-", "value": { "foo": [ "bar", "baz" ] } } ],
      "expected": [ 1, 2, [ 3, [ 4, 5, { "foo": [ "bar", "baz" ] } ] ] ]},

Nice catch! :)

**Comment by masonhunk** [comment]
wow.. maybe there is a little misunderstanding here. An naive example:
suppose we have two class named "UpDoc","DownDoc"  :
    class UpDoc
    {
        public List<DownDoc> DownDocs { get; set; }
    }
    class DownDoc
    {
        public List<int> Integers { get; set; }
    }

and we get a test case:
         public void PathTruncateTest()
        {
            DownDoc downDoc = new DownDoc() { Integers = new List<int> { 1 } };
            UpDoc upDoc = new UpDoc() { DownDocs = new List<DownDoc> { downDoc } };
           

            Operation<UpDoc> operation = new Operation<UpDoc>("replace", "DownDocs/0/Integers/0", null, 3);
            JsonPatchDocument<UpDoc> jsonPatch = new JsonPatchDocument<UpDoc>(new List<Operation<UpDoc>>() { operation });
            jsonPatch.ApplyTo(upDoc);

            Assert.Equal(3,upDoc.DownDocs[0].Integers[0]);

        }
the test case will fail, because path "DownDocs/0/Integers/0" will be truncated to "DownDocs" instead of "DownDocs/0/Integers" as we use "indexOf" when populating variable "actualPathToProperty" in ObjectAdapter.cs, so the value "3" will be applied to DownDocs property instead of DownDocs/0/Integers, in which case raising type-replated exceptions:)

**Comment by KevinDockx** [comment]
This has now been fixed.  Was a bit more complicated than just using LastIndexOf (although that was part of the solution - thanks for the help :)) - in the end, the logic for finding the correct property also had to be changed.  Current version (including quite a bit of refactoring to get this ready for supporting dynamics in Marvin.JsonPatch.Dynamic) is on my preview feed (https://www.myget.org/gallery/marvin), will be released on NuGet soon :)

**Comment by masonhunk** [comment]
recently i've been reading Marvin.JsonPatch.Dynamic source code,  and indeed this bug is fixed - Expecting next release!:)
