### ISSUE TITLE
Strong Name Assembly?

### ISSUE THREAD

**Issue by carolynvs** [KevinDockx/JsonPatch#27]
Would you be willing to strong name / sign the assembly? Before I make a private copy of the package with signed assemblies, I thought I would check first in case it's something you would consider.

If not, that's fine; I will just create a signed package, e.g. Marvin.JsonPatch.Signed, ([just as I did for Flurl](https://github.com/tmenier/Flurl/issues/39#issuecomment-115874139)) and reference that.

**Comment by KevinDockx** [comment]
Hi @carolynvs,

that's a heated subject :-)  

http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html
http://blog.maartenballiauw.be/post/2014/09/10/Automatically-strong-name-signing-NuGet-packages.aspx
http://nickberardi.com/json-net-strong-naming-and-nuget-woes/

Quite a few pro's and cons to this approach, and in the end, I'd prefer not to strong name marvin.jsonpatch.  If you look at how Json.NET finally "solved" the issues that arose with strong-naming Json.NET: that's something I'd like to avoid (=> http://james.newtonking.com/archive/2012/04/04/json-net-strong-naming-and-assembly-version-numbers )

But of course: feel free to create a signed package!  I'd suggest you wait for release 0.9 (coming up "soon"), as that includes some refactoring to ensure it's ready for dynamics support (https://github.com/KevinDockx/JsonPatch.Dynamic).

**Comment by carolynvs** [comment]
@KevinDockx Thanks for the great info! If I had my way, I'd never sign another assembly again but I have inherited a project which requires signing so... here I am. :smile: 

I'll create the signed package soon and am looking forward to the 0.9 release, the dynamic support looks very interesting.

**Comment by KevinDockx** [comment]
@carolynvs : it took a while, but 0.9 has been released :)

**Comment by carolynvs** [comment]
:+1: Thanks!
