### ISSUE TITLE
Invalid Example JSON

### ISSUE THREAD

**Issue by Charlemagne3** [KevinDockx/JsonPatch#28]
In the "To create a JsonPatchDocument directly in JSON:" example, 

```
{
    [
        { "op": "add", "path": "/foo", "value": "bar"},
        { "op": "replace", "path": "/baz", "value": "boo" }
    ]
}
```

is invalid JSON because there is no key for the array.  I am trying to deserlalize JSON as a JsonPatchDocument<SomeModel> in a WCF method in this way:

```
        [OperationContract, WebInvoke(Method = "PATCH", UriTemplate = @"Update/{id}", ResponseFormat = WebMessageFormat.Json, BodyStyle = WebMessageBodyStyle.Bare)]
        public Response PatchSomeRecord(string id, JsonPatchDocument<SomeModel> patch) {
            return PatchSomeModel(id, patch);
        }
```

Without proper JSON, I am not sure what I should put in the HTTP body.  Seeing that JsonPatchDocument has a property Operations, I passed

```
{
    "Operations": [
        {
          "op": "replace",
          "path": "/Identifier",
          "value": 12345
        }
    ]
}
```

but this did not work either, as the "Operations" field was still just an empty list.

How exactly is the JSON example intended to work?

EDIT: I Did figure out that I can pass an array of operations as JSON:

```
[
    {
        "op": "test",
        "path": "test",
        "value": "test"
    }
]
```
and deserialize that as a 
```
Operation<SomeModel>[] patches
```
and then pass that to the constructor for JsonPatchDocument, but it seems like there should be a neater way to accomplish this.

**Comment by KevinDockx** [comment]
Hi,

according to the standard, there shouldn't be an envelope name (eg: no "operations") => https://tools.ietf.org/html/rfc6902

However, I'm afraid your use case isn't supported: this component has not been tested with WCF, nor is it intended for it.  It might or might not work - but theoretically, if you're using Json.NET to deserialize, it *should* work with the example you provided.  

I will look into what the correct body for such a patch object is though: the (de)serilization is handled by Json.NET, but looking at what you wrote, it seems like the outer curly braces should indeed be removed.  Thanks for noticing, I'll investigate.

**Comment by Charlemagne3** [comment]
Well, the standard specifies a top level JSON array, which is valid JSON, but in the example there is an array nested inside of a top level object with no key.  Any value not on the top level must have a key.  

See section 6 Objects for a terse explanation of the structure:  http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

```
An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs.
A name is a string. A single colon token follows each name, separating the name from the value. A single
comma token separates a value from a following name. 
```

I also realized that I wouldn't actually want to deserialize into a JsonPatchDocument directly, because as you pointed out this would violate the standard.  The standard payload naturally maps to a list of Operations and not a JsonPatchDocument.  You might want to add this to the readme as this is the only way you could adhere to the standard for PATCH bodies.  

Also, since I am sending payloads via POSTman and not programmatically, I am not sure what exactly is produced by the example code from the readme below, but I would make sure that it adheres to the PATCH standard as well as the JSON standard for how objects are composed.

```
JsonPatchDocument<DTO.Expense> patchDoc = new JsonPatchDocument<DTO.Expense>();
patchDoc.Replace(e => e.Description, expense.Description);

// serialize
var serializedItemToUpdate = JsonConvert.SerializeObject(patchDoc);

// create the patch request
var method = new HttpMethod("PATCH");
var request = new HttpRequestMessage(method, "api/expenses/" + id)
{
    Content = new StringContent(serializedItemToUpdate,
    System.Text.Encoding.Unicode, "application/json")
};

// send it, using an HttpClient instance
client.SendAsync(request);
```

Thanks.

**Comment by KevinDockx** [comment]
Yup, you're right.  I think this could be solved by changing the custom converter used by JSON.NET for (de)serialization so it doesn't include the outer brackets when serializing yet creates a jsonpatchdoc with a list of operations from a message body that's just an array on deserialization.  Will fix :)

**Comment by KevinDockx** [comment]
Hmm, looked into this a bit better:

[
    {
        "op": "test",
        "path": "test",
        "value": "test"
    }
]

Is handled correctly by the component.  I've added a unit test for this (=> SerializationNoEnvelope in ObjectAdapterTests.cs.  It's simply the sample in the readme.md that's wrong.  I've updated the readme.md accordingly.

**Comment by KavyaShetty** [comment]
Can you update on how you overcame the invalid JSON issue as to what modification did you do in code to get your model mapped to the JsonPatchDocument. I am also using WCF REST API and am facing the same issue.

**Comment by KevinDockx** [comment]
No modification was necessary, the sample in the readme was wrong :)
