### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/JsonPatch#35]
=> get 'm in line with those from the Asp.NET version

**Comment by Cephei** [comment]
Would love to see this. Specifically, JsonPatch error codes as constants.  I'm using this library to implement the SCIM specification (https://github.com/PowerDMS/Owin.Scim).

However, SCIM's error response handling is very specific concerning patch operations.  See: [SCIM Error Handling](https://tools.ietf.org/html/rfc7644#section-3.12) - invalidFilter, invalidPath, noTarget, etc

Having explicit error codes to represent reasons for a JsonPatchException to occur would be quite helpful.  For now, I may have to look at the SuggestedStatusCode + Exception Message to parse it for keywords.  Obviously not the best option.

Thanks!

**Comment by KevinDockx** [comment]
That's a good suggestion, tnx :) I'll look into it!

**Comment by KevinDockx** [comment]
Currently the error messages are on par with the other versions of this library.  Going to close this for now.
