### ISSUE TITLE
Pluggable way to resolve actual properties

### ISSUE THREAD

**Issue by ejsmith** [KevinDockx/JsonPatch#37]
We use an underscore naming convention for our json data similar to this:

http://stackoverflow.com/questions/3922874/c-sharp-json-net-convention-that-follows-ruby-property-naming-conventions

Is there some easy way to make this naming convention work with your library?

**Comment by KevinDockx** [comment]
I'm afraid that's not a supported scenario at the moment...

**Comment by KevinDockx** [comment]
Implemented, see #44
