### ISSUE TITLE
JSON Pointer support

### ISSUE THREAD

**Issue by jvdonk** [KevinDockx/JsonPatch#38]
Hi, awesome work with the JsonPatch project.

Am I correct that the current implementation does not support the JSON Pointer syntax by a string of tokens(e.g. the key of the object) and only JSON pointer syntax by index for IList properties?

Given the following document(object, with a nested IList property):
````
{
  "foo": "bar",
  "myCollectionOfObjects": [
    {
      "id": 1234,
      "name": "1234"
    },
    {
      "id": 567,
      "name": "567"
    }
  ]
}
````
I want to be able to produce the following json patch document:
````
[
  { "op": "replace", "path": "/myCollectionOfObjects/567/name", "value": "my1234" }
]
````
whereby 567 is not the position but the key(id property).

Currenty I find myself able to produce the following patchdoc:
````
[
  { "op": "replace", "path": "/myCollectionOfObjects/1/name", "value": "my1234" }
]
````
With the following syntax:
````
patchDoc.Replace<string>(x => x.myCollectionOfObjects[1].name, "my1234")
````

Instead of maybe the following syntax:
````
patchDoc.Replace<string>(x => x.myCollectionOfObjects["567"].name, "my1234")
````

Any suggestions? Tnx!

**Comment by KevinDockx** [comment]
Hi, 

glad you like this project!  You're correct, that is currently not supported.  And I'm sorry to say I don't think it should be... - how would we be able to tell the difference between 567 (key) and 567 (index)?  I quickly scanned through the Json Pointer standard (https://tools.ietf.org/html/rfc6901), which states: 

>If the currently referenced value is a JSON array, the reference
      token MUST contain either:

  >    characters comprised of digits (see ABNF below; note that
         leading zeros are not allowed) that represent an unsigned
         base-10 integer value, making the new referenced value the
         array element with the zero-based index identified by the
         token
> or  exactly the single character "-", making the new referenced
         value the (nonexistent) member after the last array element."

So I'm afraid implementing this would violate the standard...

**Comment by jvdonk** [comment]
Yes, I see that now. I must have misinterpreted the specification. Thank you anyway! :)

**Comment by KevinDockx** [comment]
No problem :)
