### ISSUE TITLE
Does JsonPatchDocument require additional codes to deserialize properly?

### ISSUE THREAD

**Issue by funchiat** [KevinDockx/JsonPatch#40]
HTTPPatch document via a hand typed JSON format has been accepted via Fiddler
[{"value":false,"path":"/isapprovalaccepted","op":"replace"}]

But, inside my .NET project, JsonConvert deserialize the document into format
{"Operations":[{"OperationType":2,"value":false,"path":"/isapprovalaccepted","op":"replace"}]}

====
Which, patch document passed as null into my controller and causes exception.
[HttpPatch]
public IHttpActionResult Patch(int ID, [FromBody]JsonPatchDocument<ProjekApproval> patchData)
patchData.ApplyTo(approvalItemUpdate);   // exception here

===
My question is, how can I serialize/deserialize correctly?
using Marvin.JsonPatch;
using Newtonsoft.Json;
JsonPatchDocument<ProjekApproval> patchDoc = new JsonPatchDocument<ProjekApproval>();
patchDoc.Replace(b => b.IsApprovalAccepted, false);
var serializedItemToUpdate = JsonConvert.SerializeObject(patchDoc);

'ProjekApproval' type is actual model in Entity Framework where IsApprovalAccepted is boolean

**Comment by funchiat** [comment]
public IHttpActionResult Patch(int ID, JObject patchData)
Yes parse into JObject is
{{
  "Operations": [
    {
      "OperationType": 2,
      "value": false,
      "path": "/isapprovalaccepted",
      "op": "replace"
    }
  ]
}}

---
public IHttpActionResult Patch(int ID, [FromBody]JsonPatchDocument patchData)
null

Runtime version from client and API are both v4.0.30319

I need to figure out what to do

**Comment by KevinDockx** [comment]
Hi,

- if you serialize a JsonPatchDocument, the serializer uses a custom converter (TypedJsonPatchDocumentConverter) that takes care of ensuring there's no "Operations" property in the serialized result. 

- sending such a serialized JsonPatchDocument to the API will again trigger the custom converter, which will put the list of operations in an Operations property.

Have a look at the unit tests in the source code for a ton of examples - you'll notice that when serializing, the "Operations" property is removed from the result. 

One thing I do notice in your code: you're trying to deserialize to a non-generic JsonPatchDocument. Maybe you can try having your Patch method at API level accept the correctly typed version?

If all else fails, feel free to send me a demo project - I'll have a look :)

**Comment by funchiat** [comment]
oh no no there is a generic class to JsonPatchDocument

Try typing this without spaces in this textbox and the projekapproval generic will poof/dissappear

Here's the right signature where JsonPatchDocument does have generic class that matches client.
[FromBody]JsonPatchDocument < ProjekApproval > patchData)


This line of code works
            JsonPatchDocument<ProjekApproval> orderWrapper = JsonConvert.DeserializeObject< JsonPatchDocument < ProjekApproval > >(
                "[{\"value\": false, \"path\": \"isapprovalaccepted\",\"op\": \"replace\"}]");

So I will look at the unit tests to see how this can be done somehow with custom converter

**Comment by funchiat** [comment]
Thanks for your suggestion to check out the source project. The codes were straightforward I could not understand what could go wrong internally, at first. Later, I suspect some versioning issue. 
I do not know the exact cause but I resolved the issue via reinstallation.

First, I downloaded entire fresh source from my source control.
In fact, old project referenced in original question in this post can no longer start . Some error
Method not found: 'Void Newtonsoft.Json.Serialization.DefaultContractResolver.set_IgnoreSerializableAttribute(Boolean)'.
I am going to delete the whole folder later.

I update the package Newtonsoft from version 6 to version 8 inside Marvin.Json project here in GitHub. Compile and rebuild. Copy output Marvin.JsonPatch.dll library into my other project \bin folder and reference it manually via Add-Reference. This means, I did not attempt NuGet the latest Marvin here. This main project here is the one that use JsonConvert on patchDoc.

Marvin.JsonPatch.JsonPatchDocument < ProjekApproval > patchDoc = new Marvin.JsonPatch.JsonPatchDocument < ProjekApproval > ();
patchDoc.Replace(b = > b.IsApprovalAccepted, false);
var serializedItemToUpdate = JsonConvert.SerializeObject(patchDoc);

In this main project, I NuGet the latest Newtonsoft version 6 into version 8 as well, just like how I did for Marvin.JsonPatch project earlier.

Back in my web api project,
public IHttpActionResult Patch(int ID, [FromBody]JsonPatchDocument < ProjekApproval >  patchData) is no longer null. There are no fixes needed here

In my old codes, I started with NuGet latest Newtonsoft.Json and latest Marvin.JsonPatch.
However, Marvin.JsonPatch comes default old version of Newtonsoft.Json internally. 

Do you think that could be potential cause?

**Comment by KevinDockx** [comment]
Glad to read it worked out :)   By default, Marvin.JsonPatch requires an older version indeed, but newer versions should still work.  Hard to say what exactly the problem was... :(    One thing I can think about: when you're working with different versions of external libraries (like Json.NET) and upgrade/downgrade via NuGet, always check the web.config files: they may contain assembly redirects that aren't automatically adjusted/deleted when changing the version.

**Comment by funchiat** [comment]
Maybe the exception/problem was rooted in Json. So they wrote something like
try
{
 .... ...
}
catch
{
 return null
}

Finally, just kidding

**Comment by zinov** [comment]
What if you have 2 different Content-Types with a Patch verb in use and you need to apply a model binder to choose correctly which JsonPatch<Dto> you need to deserialize? 

For example 

`using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Data.Web.Api1.Dtos;
using Microsoft.AspNetCore.JsonPatch;
using Web.Framework.Helpers.MediaTypes;

namespace Web.Api1.ModelBinder
{
    public class WeatherForecastForPatchModelBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
                throw new ArgumentNullException(nameof(bindingContext));

            string valueFromBody = string.Empty;

            using (var sr = new StreamReader(bindingContext.HttpContext.Request.Body))
            {
                valueFromBody = sr.ReadToEndAsync().GetAwaiter().GetResult();
            }

            if (string.IsNullOrEmpty(valueFromBody))
            {
                return Task.CompletedTask;
            }

            string contentType = bindingContext.HttpContext.Request.Headers.FirstOrDefault(x => x.Key == HeaderNames.ContentType).Value;
            dynamic model = null;

            var isDeserializingOk = true;

            switch (contentType)
            {
                case HttpMediaTypes.WeatherForecastType1:
                    try
                    {
                        model = JsonConvert.DeserializeObject<JsonPatchDocument<WeatherForecastForUpdateDto1>>(valueFromBody);
                    }
                    catch
                    {
                        isDeserializingOk = false;
                    }
                    break;
                case HttpMediaTypes.WeatherForecastType2:
                    try
                    {
                        model = JsonConvert.DeserializeObject<JsonPatchDocument<WeatherForecastForUpdateDto2>>(valueFromBody);
                    }
                    catch
                    {
                        isDeserializingOk = false;
                    }
                    break;
            }

            if (!isDeserializingOk)
            {
                bindingContext.Result = ModelBindingResult.Failed();

                return Task.CompletedTask;
            }

            bindingContext.Result = ModelBindingResult.Success(model);

            return Task.CompletedTask;
        }
    }
}
`

The JsonConverter fails in this case `JsonConvert.DeserializeObject`
