### ISSUE TITLE
Honoring Microsoft.AspNet.Mvc.BindAttribute

### ISSUE THREAD

**Issue by AymanGaafar** [KevinDockx/JsonPatch#41]
Can this component honor the BindAttribute ?

i.e. If the class type that is being patched has an MVC BindAttribute and does not include certain property(ex: Prop1), then if Prop1 was found in the operations passed from the client, it will just be ignored.

**Comment by KevinDockx** [comment]
I'm afraid that's currently unsupported.

**Comment by AymanGaafar** [comment]
If this component supports the BindAttribute checking, it would be awesome since in many cases (I think) it would replace MVC's default model binding (which already checks the BindAttribute).

**Comment by NicoJuicy** [comment]
You shouldn add a dependency to Web.Mvc in a project, create a seperate project which has both dependencies and add it there :)

**Comment by KevinDockx** [comment]
Looked into this, and on further inspection it appears that implementing this would violate the standard - operations shouldn't be ignored.
