### ISSUE TITLE
Support for SL 5 in the PCL

### ISSUE THREAD

**Issue by NicoJuicy** [KevinDockx/JsonPatch#42]
Would it be possible to add support for Silverlight 5 in the PCL class + nuget package?

**Comment by KevinDockx** [comment]
As Silverlight is currently not under active development anymore, I don't really have plans to add support for it, sorry...  But you can of course try to download the code & change PCL framework support if you really need it.

**Comment by NicoJuicy** [comment]
Valid reason ( sorry for the delay though).
