### ISSUE TITLE
Using JsonPatch with TFS 2015 REST API

### ISSUE THREAD

**Issue by bbusacker** [KevinDockx/JsonPatch#43]
Kevin,

I'm trying to use JsonPatch to do work item updates that use the the PATCH command.  My problem is that Microsoft uses paths like /fields/System.Description for a property in the model class called just Description.  I use the JsonProperty attribute class from the Newtonsoft.Json library to deserialize the class properly and that works  but when I use the JsonPatch document it does not honor these values.  Any thoughts?

Instead the path /fields/Description gets created which is not correct.

**Comment by KevinDockx** [comment]
Work in progress - component should honor JsonProperty attributes, will implement with IContractResolver.

**Comment by KevinDockx** [comment]
JsonProperty is now honoured when applying a patchdoc (cfr #44 ) - custom ContractResolver & honouring JsonProperty when working with a generic JsonPatchDocument are split up in #51 & #50
