### ISSUE TITLE
Patching operations break on properties with the new keyword

### ISSUE THREAD

**Issue by KevinDjordjevic** [KevinDockx/JsonPatch#46]
Here's the exception:

Marvin.JsonPatch.Exceptions.JsonPatchException was unhandled by user code
  HResult=-2146233088
  Message=Patch failed: property at location path: /IAmProperty does not exist
  Source=Marvin.JsonPatch
  SuggestedStatusCode=422
  StackTrace:
       at Marvin.JsonPatch.Adapters.ObjectAdapter`1.Remove(String path, T objectToApplyTo, Operation`1 operationToReport)
       at Marvin.JsonPatch.Adapters.ObjectAdapter`1.Replace(Operation`1 operation, T objectToApplyTo)
       at Marvin.JsonPatch.JsonPatchDocument`1.ApplyTo(T objectToApplyTo, IObjectAdapter`1 adapter)
  InnerException: 

Here's a test situation that breaks:

```
    public class TestsController : ApiController
    {
        [HttpPatch]
        [VersionedRoute("api/Tests/{id}", 1)]
        public IHttpActionResult PatchTest(int id, JsonPatchDocument<DerivedTest> patchDocument)
        {
            patchDocument.ApplyTo(new DerivedTest());
            return Ok();
        }
    }

    public class Derived : Base
    {
        public new IReadOnlyDictionary<string, string> IAmProperty { get; set; }
    }

    public class Base
    {
        public Hashtable IAmProperty { get; set; }
        public string IAmAlsoProperty { get; set; }
    }
```

Request Body:

[
    { "op": "replace", "path": "/IAmProperty", "value": {"Rip": "Ship"}}
]

**Comment by KevinDjordjevic** [comment]
I've got a fix for this on my local machine. Be on the lookout for a pull request.

**Comment by KevinDockx** [comment]
Thanks for catching this - PR is welcome ;-)

**Comment by KevinDockx** [comment]
Merged.
