### ISSUE TITLE
JsonPatchDocument.Replace lowercasing path poses problem for manual patching

### ISSUE THREAD

**Issue by jeffdahl** [KevinDockx/JsonPatch#54]
When an object has mixed case attributes, (e.g. a Cat object with a boolean property hasStripes) the path is forced to lowercase.  

When consuming the patch document, the path is not the case of the entity property.  In the example above, the path changed from `/hasStripes` to `/hasstripes`.

**Comment by KevinDockx** [comment]
Hi @jeffdahl: in .NET, case sensitivity for property names is non-CLI compliant - so if you manually want to patch, the casing of the property name of the .NET class should be ignored.

**Comment by jeffdahl** [comment]
I see.  I will ignore case on the path.

Thank you for your great implementation.  Congratulations on hitting release 1.0.

**Comment by KevinDockx** [comment]
Thanks! :-)
