### ISSUE TITLE
Need help implementing IObjectAdapater

### ISSUE THREAD

**Issue by deepak-khopade-isdr** [KevinDockx/JsonPatch#57]
Hi Kevin,

I am struggling from hours today to better implement the IObjectAdapter. As suggested by you I have created a class which implements those 6 ops , however, I am not sure how am I gonna use it from my controller. I tried to pass this new class to patch.ApplyTo() method but its not hitting those methods.

Can you please put more light on it? any help is highly appreciated. Thanks.

**Comment by CharlesBean** [comment]
Not sure if you ever figured this out or not, but for future readers I believe the solution is to use the other definition of ApplyTo(), which takes an IObjectAdapter as the second parameter

`public void ApplyTo(T objectToApplyTo, IObjectAdapter<T> adapter);`

I usually look through the unit tests for projects that are missing some key documentation like this. Often it can be even more helpful than documentation. Hope this helps someone

**Comment by deepak-khopade-isdr** [comment]
Hey @CharlesBean, thanks for your response, and I figured this out long back exactly the way you have explained :)... appreciate your response though.

**Comment by KevinDockx** [comment]
I'll close this as it seems to be solved - if it needs to be reopened, just ask :)

**Comment by deepak-khopade-isdr** [comment]
Thanks @KevinDockx :+1:
