### ISSUE TITLE
Mechanism to exclude properties?

### ISSUE THREAD

**Issue by dorlandode** [KevinDockx/JsonPatch#59]
Is there a way to exclude properties from being patched in your library?  For example, one user may be able to patch a property, but another use is not able to based on a role or permission.  

Basically, I am wondering if there is a way to add some configuration to the JsonPatchDocument object to exclude certain properties.  Or maybe handle when properties a user is not authorized to be modified are attempted and throw a 403 or something like that.

**Comment by KevinDockx** [comment]
You cannot block creating an operation on a specific property, but what you could do is manipulate the Operations collection (on JsonPatchDocument) before applying the patch document at API level.  In your action, you can look at the rights of the user or whatever other business rule you might have and remove operations if a certain condition isn't met (and if that condition isn't met, you can of course return any status code you want from your API action).

**Comment by dorlandode** [comment]
Awesome, that was the route I headed down, thank you.
