### ISSUE TITLE
Unable to add to custom objects that implement IEnumerable<T>

### ISSUE THREAD

**Issue by rorrell** [KevinDockx/JsonPatch#60]
We frequently create our own enumerable types for our objects, which generally either implement IEnumerable<T> directly or inherit from one of its implementations (i.e., List<T>).  "Add" operations to add to an object of that sort fail.  The actual error message is:

> Patch failed: provided value is invalid for array property type at location path...

On visual inspection of this code base, the suspicion is that PropertyHelpers.GetEnumerableType is not returning unexpected results for this case.

Here's an example of how one of our collection objects might be defined: 

`class Cars : List<Car> { }`

**Comment by KevinDockx** [comment]
Thanks for reporting this - this should work, so I'll file it as a bug to look into.

**Comment by rorrell** [comment]
Terrific, thanks!

**Comment by KevinDockx** [comment]
I just added a few tests for this (e20a9aad4e4b10eb4578a088cc6f8f7c2a2ca277), and this seems to work as expected.  Could you have a look?  Maybe I missed something in these tests.

**Comment by rorrell** [comment]
The tests do appear to cover the appropriate object types.

**Comment by KevinDockx** [comment]
Ok, I'm going to close this then.

**Comment by rorrell** [comment]
Sounds good.  When can I expect it to be incorporated into a release?

**Comment by KevinDockx** [comment]
Every time someone commits something to this repo, a new NuGet package gets created on my MyGet feed: https://www.myget.org/feed/Packages/marvin  

You can always use that to get the "latest and greatest" version.   As far as creating a new version for NuGet is concerned: that'll be released once I backport this issue: #58  (pretty big refactoring).
