### ISSUE TITLE
Implement Test operation

### ISSUE THREAD

**Issue by KevinDockx** [KevinDockx/JsonPatch#61]
The "test" operation tests that a value at the target location is equal to a specified value.

**Comment by imukai** [comment]
Being a year+ is this still on the radar somewhere?  I'm trying to find a non-core API implementation of Json Patch that isn't dead in the water.

**Comment by KevinDockx** [comment]
Tbh this feature is pretty far down the backlog, as you might've guessed.  But if you really need this operation I (or anyone else who wants to help out :)) could have a look at how easy/hard it would be to backport this (the core implementation has recently implemented the Test operation).

**Comment by KevinDockx** [comment]
Implemented :)
