### ISSUE TITLE
Warning in .Net 4.6.2

### ISSUE THREAD

**Issue by mathimaz** [KevinDockx/JsonPatch#68]
Works great but i get 1 warning when compiling a .Net 4.6.2 project: 

> Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

In the build output:

> ...
> 7>  **There was a conflict between "mscorlib, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089" **and "mscorlib, Version=2.0.5.0**, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
> 7>      "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
> ...
> 7>      **References which depend on "mscorlib, Version=2.0.5.0**, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
> 7>          C:\Vault\UZG\PBS\current\NET40\PBS\packages\Marvin.JsonPatch.1.0.0\lib\portable40-net40+win8+wpa81\ **Marvin.JsonPatch.dll**
> 7>            Project file item includes which caused reference "C:\Vault\UZG\PBS\current\NET40\PBS\packages\Marvin.JsonPatch.1.0.0\lib\portable40-net40+win8+wpa81\Marvin.JsonPatch.dll".
> 7>              Marvin.JsonPatch, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL
> 7>  **There was a conflict between "System.Core, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089" **and "System.Core, Version=2.0.5.0**, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
> 7>      "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
> 7>      References which depend on "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Core.dll].
> ...
> 7>      **References which depend on "System.Core, Version=2.0.5.0**, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
> 7>          C:\Vault\UZG\PBS\current\NET40\PBS\packages\Marvin.JsonPatch.1.0.0\lib\portable40-net40+win8+wpa81\ **Marvin.JsonPatch.dll**
> 7>            Project file item includes which caused reference "C:\Vault\UZG\PBS\current\NET40\PBS\packages\Marvin.JsonPatch.1.0.0\lib\portable40-net40+win8+wpa81\Marvin.JsonPatch.dll".
> 7>              Marvin.JsonPatch, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL
> ...
>

**Comment by KevinDockx** [comment]
Tried reproducing this by starting a new .NET 4.6.2 project and adding the package.  I don't get any warnings... maybe something to do with your local configuration?  Closing for now.
