### ISSUE TITLE
Camel Case not supported in the Path's Properties

### ISSUE THREAD

**Issue by mtzaldo** [KevinDockx/JsonPatch#70]
I have the following case:

`public class Product 
{
    public string Name { get; set; }
    [JsonProperty(PropertyName="shortCode")]
    public string ShortCode { get; set; }
}`

if I want to replace the ShortCode to PROD1 for example, it produces the following json:
`[
    {"value":"PROD1","path":"/shortcode","op":"replace"}
]`

but I really wanted the following:

`[
    {"value":"PROD1","path":"/shortCode","op":"replace"}
]`

Also note that the PropertyName from JsonProperty is ignored and it always convert to lower case.

**Comment by leemicw** [comment]
@KevinDockx we have a similar issue.  Our generic objects are pascal case and we want to maintain that in the JSON output.  Would you be open to a pull request that leaves the current behavior in place but allows you to override with a new parameter to the JsonPatchDocument ctor or with custom attributes on the generic class or property names?  

If you are what things should be consider as we are working on it? 

Thanks,
Michael

**Comment by KevinDockx** [comment]
I'm definitely open to a PR for this, that would be very helpful as I'm quite limited on time (as you can probably guess from the delay in replying to issues / working on this component :)).  One important thing to keep in mind is that when comparing property names when applying the operations, casing shouldn't be taken into account (as differently cased property names in the same class are technically possible, but those are not CLR-compliant)

**Comment by leemicw** [comment]
Great.  I will get started this afternoon and will have something for you to review today or Monday.

**Comment by mtzaldo** [comment]
I downloaded the code the other day and implemented the camel case, lower case and capital case for this. I haven't had the time to send the changes... @leemicw  If you like, I can send you the code I have and you can take a look at that... I hope it helps...

**Comment by leemicw** [comment]
@mtzaldo that would be great.  if you can push it somewhere on github or send me a zip file I can get started.  michael@michaelware.net

**Comment by mtzaldo** [comment]
@leemicw I will send you the code around 5:00-6:00pm today.

**Comment by mtzaldo** [comment]
@leemicw Here is the code with the changes I made. I set one variable in the empty constructor to specify the type of conversion... let me know if you have any question. I will send this code by email too.
[JsonPatch.zip](https://github.com/KevinDockx/JsonPatch/files/1099026/JsonPatch.zip)

**Comment by KevinDockx** [comment]
Just published v1.1 to NuGet - thanks for your help! :-)

**Comment by leemicw** [comment]
@KevinDockx Thank you for accepting and publishing a new version.  Glad we could all work on it together.
