### ISSUE TITLE
What's the recommended way to specify a JsonPatchDocument in swagger?

### ISSUE THREAD

**Issue by paulomorgado** [KevinDockx/JsonPatch#71]

**Comment by leemicw** [comment]
@paulomorgado if you are using Swashbuckle to generate the the Swagger JSON from your classes you can use the same solution we did.  

[http://michaelware.net/2017/06/17/Using-Marvin-JsonPatch-and-Swashbuckle-to-Generate-Swagger-Documents/](http://michaelware.net/2017/06/17/Using-Marvin-JsonPatch-and-Swashbuckle-to-Generate-Swagger-Documents/)

disclaimer, that's my blog.

**Comment by paulomorgado** [comment]
Thanks!

**Comment by KevinDockx** [comment]
Thanks for this, closing issue :)
