### ISSUE TITLE
Error code 400 in c# using Json patch

### ISSUE THREAD

**Issue by elikhater** [KevinDockx/JsonPatch#78]
I am getting an error code of 400 when I run the following code. Any ideas as to why this would happen. Please note that value is an array and not just one variable to be patched:
            var client = getApiClient();
            var ticketsApi = new TicketsApi(client);

            CustomFieldValue mycus = new CustomFieldValue
            {
                Id = 2,
                Caption = "Cust Test",
                EntryMethod = CustomFieldValue.EntryMethodEnum.List,
                NumberOfDecimals = 0,
                Type = CustomFieldValue.TypeEnum.Text,
                Value = "Color - Red"
            };

            string val = mycus.ToJson();
            var patchOperations = new List<PatchOperation>
            {
                new PatchOperation
                {
                    Op = "replace",
                    Path = "/customFields",
                    Value = "[ " + val + " ]"
                }
            };
            var updateResponse = ticketsApi.UpdateTicketById(prmTicketId, patchOperations);

**Comment by KevinDockx** [comment]
Do you get the error when applying the patch, or do you get it when deserializing the JsonPatchDocument?

**Comment by elikhater** [comment]
Hi Kevin,
I get it when I apply the patch. my new code now looks like this:

            var client = getApiClient();
            var ticketsApi = new TicketsApi(client);

            CustomFieldValue mycustom = new CustomFieldValue();
            {
                mycustom.Id = 2;
                mycustom.Caption = "test";
                mycustom.Value = "testvalue";
                mycustom.NumberOfDecimals = 0;
            }

            string mypatchval = JsonConvert.SerializeObject(mycustom,
Formatting.Indented);

            var patchOperations = new List<PatchOperation>
            {
                new PatchOperation
                {
                    Op = "replace",
                    Path = "/customFields",
                    Value = mypatchval
                }
            };

            var updateResponse = ticketsApi.UpdateTicketById(1111,
patchOperations);

**Comment by KevinDockx** [comment]
Ok, so, if you apply the patch, you should get a more specific exception: either a JsonPatchException for something the lib handles, or a more generic Exception for something that might point to a bug.  What's the content/stacktrace of that exception?

**Comment by KevinDockx** [comment]
I'll close this as this has become inactive - if it needs to be reopened, just ask :)

**Comment by elikhater** [comment]
Thank you.
