### ISSUE TITLE
EnumMember usage causes JsonPatchException

### ISSUE THREAD

**Issue by imukai** [KevinDockx/JsonPatch#82]
Given an enum:

```
    public enum Status    {
        Unknown  = 0,
        Open = 1,
        [EnumMember(Value = "in_progress")]
        InProgress = 2,
        Closed = 3
    }
```
Patching by integer value or regular enum string value is fine, but trying to use the EnumMember value blows up with a JsonPatchException:

>     "Message": "An error has occurred.",
>     "ExceptionMessage": "The value 'in_progress' is invalid for target location.",
>     "ExceptionType": "Marvin.JsonPatch.Exceptions.JsonPatchException",
>     "StackTrace": "   at Marvin.JsonPatch.Internal.ErrorReporter.<>c.<.cctor>b__1_0(JsonPatchError e)\r\n   at Marvin.JsonPatch.Adapters.ObjectAdapter.Add(String path, Object value, Object objectToApplyTo, Operation operation)\r\n   
>     .. snip

I had already globally registered Newton's StringEnumConverter which allows handling of EnumMember

`config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new StringEnumConverter());
`

But this doesn't seem to have any effect on JsonPatch.

My workaround for now  is to specifically add the converter to the enum class.

```
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status
    ...
```
This works, but I am confused why the globally-registered converter doesn't filter down into JsonPatch.  Any ideas?

This is a WebApi project (framework 4.6.2) if that matters.

**Comment by KevinDockx** [comment]
This is because JsonPatch uses a custom converter (JsonPatchDocumentConverter, JsonPatchDocumentConverterOfT) for the patchdoc instead of the built-in/registered converters.  When using such a custom converter, the converter(s) specified in serializersettings are ignored.  Are you ok with using the workaround?

**Comment by imukai** [comment]
I am ok with the workaround -- was mainly curious if you were aware of it and if you knew any global tricks to fixing it.  I'm actually trying to get them away from using enums because this EnumMember thing causes some headaches elsewhere also.
