### ISSUE TITLE
Is it possible to create a patch document using reflection

### ISSUE THREAD

**Issue by noufionline** [KevinDockx/JsonPatch#84]
Hi @KevinDockx ,

I am using an open source tool called Trackable Entities, which has a TrackableCollection<T> implementation which gives me the DTO with a collection of Modified Properties.

```csharp
 public List<string> ModifiedProperties{get;set;}
```

I want to make a patch document for all the modified properties using reflection. Is it possible?

**Comment by KevinDockx** [comment]
Sure :)  In your case you could run through that ModifiedProperties list, use reflection to get the actual value of those properties on your DTO, and add a replace operation for each change.

**Comment by noufionline** [comment]
Thanks, @KevinDockx. I have another issue as well. JsonPatchDocument is updating all the values in the child collection items instead of only the changed one. It works perfectly with the Parent object where the actual Apply operation is done. But the child items it replaces every single property with the default value if not in patch document

**Comment by KevinDockx** [comment]
Hmm, that's strange... do you have a bit of sample code I can use to check?

**Comment by Anil86** [comment]
I used following helper function to obtain changed property's path & value:

    // Finds changed property's path & value from property's name
    // w/ the help of reflection
    (Expression<Func<TModel, object>> path, object value) FindOperationArguments<TModel>(TModel model,
                string propertyName)
    {
            // Get info about changed property
            PropertyInfo propertyInfo = typeof(TModel).GetProperty(propertyName,
                    BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);


            // Creates Expression<Func<TModel, object>> for obtaining path
            ParameterExpression parameter = Expression.Parameter(typeof(TModel), "p");
            MemberExpression property = Expression.Property(parameter, propertyInfo);
            Expression<Func<TModel, object>> path = Expression.Lambda<Func<TModel, object>>(property, parameter);


            object value = propertyInfo.GetValue(model);   // Gets changed property's value


            return (path, value);
    }
