### ISSUE TITLE
Is there a method to check specified fields inside a JSONPatch

### ISSUE THREAD

**Issue by dpescatore** [KevinDockx/JsonPatch#87]
Is there a method to check if a specific field is interessed by an Operation of a JsonPatchDocument?

I'd like to avoid cicle over Operations and check paths one by one.

It could be better to have a specific method.

Thanks

**Comment by KevinDockx** [comment]
Seem to have missed this year-old question :-(  Anyway, no, that doesn't exist at the moment - but I'm open to PRs :-)
