### ISSUE TITLE
Question Re: mediaType

### ISSUE THREAD

**Issue by Donnchadha** [KevinDockx/JsonPatch#92]
Kevin, you mentioned - The "application/json-patch+json" media type is used to identify such patch documents.

In the example code, "application/json" is used for the mediaType.

var request = new HttpRequestMessage(method, "api/expenses/" + id)
{
    Content = new StringContent(serializedItemToUpdate,
    System.Text.Encoding.Unicode, "application/json")
};

Why was "application/json-patch+json" not used?

**Comment by KevinDockx** [comment]
The correct type is indeed application/json-patch+json, yet most APIs will also accept application/json.  In fact, any endpoint should (preferably) accept application/json for its "default input type", and support additional (or more specific) media types when possible.  I personally prefer being as specific as possible, so I tend to use application/json-patch+json even if an API also supports application/json.  

Hope this clarifies things :)
