### ISSUE TITLE
Patch operation replace does not support value replacement of a property in a an element in an array 

### ISSUE THREAD

**Issue by haimsabo** [KevinDockx/JsonPatch#96]
Consider the following FAKE class and instances examples
```
class A
    {
        public List<B> BList { get; set; }
    }
    class B
    {
        public string Name { get; set; }
    }
```

patch document looks like this:
{"op":"replace", "path":"/blist/0/name", "value":"plain"}
trying to apply the patch document results
Marvin.JsonPatch.Exceptions.JsonPatchException`1: 'Patch failed: property at location path: /blist/0/name does not exist'

**Comment by KevinDockx** [comment]
That's expected behavior: you're trying to patch a property of an array item, but the array item doesn't exist.  If you initialize the array with 1 one, it'll work.  

Eg: 

```
class A
{
    public List<B> BList { get; set; } = new List<B>() { new B() { Name = "onevalue" } };
}
class B
{
    public string Name { get; set; }
}
```
