### ISSUE TITLE
Please release signed assemblies for latest version

### ISSUE THREAD

**Issue by joem-msft** [KevinDockx/JsonPatch#99]
It seems that the dlls in the pkg on NuGet.org are not signed and therefore cannot be consumed by my project.

Can you ensure that dlls get signed?
Or release a new Marvin.JsonPatch.Signed package for the latest version.

Thanks!

**Comment by KevinDockx** [comment]
Hi Joe, the Marvin.JsonPatch.Signed package isn't authored/created by me, so I don't have control over that.  I believe it was created by the person who opened this issue: https://github.com/KevinDockx/JsonPatch/issues/27

In that issue I also explain why I don't want to create signed assemblies for this package.  Hope that clarifies things a bit :)
